apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: strimzi-operator
    server: https://kubernetes.default.svc
  source:
    path: strimzi-operator
    repoURL: https://github.com/anandgupta0404/kafka.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy: {}