name: argocd-deploy

on:
  push:
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out Repository
        uses: actions/checkout@v3

      - 
        name: pull kubeconfig
        run: |
          mkdir ~/.kube/
          cp -p config ~/.kube/
          ls -lrt ~/.kube/config

      -
        name: Run Script file
        run : |
  
          chmod +x deploy.sh
          ./deploy.sh
        shell: bash 
    