name: argocd-deploy

on:
  push:
    branches:
      - main
    paths:
       - strimzi-kafka-operator/deploy
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - 
        name: pull kubeconfig
        working-directory: deploy
        run: |
          mkdir ~/.kube/
          cp -p config ~/.kube/
          ls -lrt ~/.kube/config

      -
        name: Run Script file
        working-directory: deploy
        run : |
  
          chmod +x deploy.sh
          ./deploy.sh
        shell: bash 
    