apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  #clientsCa:
    #generateCertificateAuthority: false
  kafka:
    image: docker.io/anand0404/principa-builder-class:latest
    imagePullPolicy: never
    authorization:
      type: simple
    version: "3.8.0"
    config:
      principal.builder.class: cz.scholz.customprincipalbuilder.CustomPrincipalBuilder
      inter.broker.protocol.version: '3.6'
      inter.broker.listner.name: internal
      auto.create.topics.enable: false
      log.message.format.version: "2.3"
      log.retention.bytes: 1073741824
      log.retention.hours: 1
      log.retention.check.interval.ms: 300000
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      min.insync.replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    resources: {}
    storage:
      deleteClaim: false
      size: 2Gi
      type: ephemeral
      class: fast
  zookeeper:
    #image: docker.io/anand0404/principa-builder-class:latest
    #imagePullPolicy: never
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
    resources: {}
    storage:
      deleteClaim: false
      class: fast
      size: 2Gi
      type: ephemeral
