apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operations:
          - All
        host: '*'
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
        host: '*'
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
        host: '*'