name: argocd-deploy

on:
  push:
env:
  CLUSTER_KUBECONFIG: ${{ secrets }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out Repository
        uses: actions/checkout@v3
      -
        name: Run Script file
        run : |
          cp 
          chmod +x deploy.sh
          ./deploy.sh
        shell: bash
    