name: ci

on:
  push:
    branches:
      - main
    paths:
      - strimzi-kafka-operator/PrincipalBuilderClass
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out Repository
        uses: actions/checkout@v4
      - 
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      -   
        name: Packaging Jar
        id: packaging-jar
        working-directory: PrincipalBuilderClass
        shell: bash
        run: |
          mvn -f pom.xml clean install
          ls -lrt
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: PrincipalBuilderClass/
          file: ./PrincipalBuilderClass/Dockerfile
          push: true
          tags: anand0404/principa-builder-class:latest
