name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out Repository
        uses: actions/checkout@v3
        with:
         path: strimzi-kafka-operator/PrincipalBuilderClass
      - 
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      -   
        name: Packaging Jar
        id: packaging-jar
        shell: bash
        run: |
          cd PrincipalBuilderClass
          mvn -f strimzi-kafka-operator/PrincipalBuilderClass/pom.xml clean install
          ls -lrt
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
